nome = str(input('Digite seu nome completo:')).strip()
print('Seu nome em maiúscula é {}'.format(nome.upper()))
print('Seu nome em minúsculas é {}'.format(nome.lower()))
print('Seu nome tem {} letras'.format(len(nome)-nome.count(' ')))
prinome = nome.split()
print('O nome {} tem {} letras'.format(prinome[0], len(prinome[0])))
